actionsdk/actionsdk.go
Allow serverless functions to inspect the event data, user data, action results, etc.
=> Add baggage

funcs.go, handler.go, handler_test.go
Adds the RateLimit config option to function definitions.
=> Add rate limiting to the Go SDK

.github/workflows/go.yml, funcs.go, handler.go, handler_test.go, internal/sdkrequest/manager.go
Allows:
```
CreateFunction(
FunctionOpts{Name: "my func name"},
EventTrigger("test/event.a"),
func(ctx context.Context, event Input[any]) (any, error) {
},
)
```
=> Fix input any on inngest.CreateFunction

handler.go
Before this change, the code was reporting relative url such as `/api/inngest` to dev server. This fixes it to have the correct url for discovery.
This fixes #18 for me, but beware that I only tested it locally with Dev Server.
Edit: I'm using this on production and it seems to work with Inngest Cloud as well
=> Fix reported URL

handler.go, handler_test.go, net.go, signature.go, signature_test.go
Add signing key rotation support. The changes in this PR must be enough to implement:
- The `INNGEST_SIGNING_KEY_FALLBACK` env var and its proper usage ([spec](https://github.com/inngest/inngest/blob/main/docs/SDK_SPEC.md#31-critical-variables))
- The new introspection endpoint logic ([spec](https://github.com/inngest/inngest/blob/main/docs/SDK_SPEC.md#45-introspection-requests))
=> Add signing key rotation support

handler.go
A recent PR mistakenly removed the env header
=> Fix missing env header

go.mod, go.sum, handler.go, handler_test.go, signature.go, signature_test.go, vendor/github.com/inngest/expr/engine.go, vendor/github.com/inngest/expr/expr.go, vendor/github.com/inngest/expr/parser.go, vendor/github.com/inngest/inngest/pkg/expressions/aggregator.go, vendor/github.com/inngest/inngest/pkg/sdk/sdk.go, vendor/github.com/inngest/inngest/pkg/syscode/codes.go, vendor/github.com/inngest/inngest/pkg/syscode/error.go, vendor/github.com/inngest/inngest/pkg/telemetry/histogram.go, vendor/golang.org/x/sync/semaphore/semaphore.go, vendor/modules.txt
Add a "trust probe". This probe can be used to establish trust between an Inngest server and an SDK.
The probe has a simple purpose: send a signed response back to an Inngest server. The Inngest server can validate the response signature to guarantee that the SDK has the correct signing key
=> Add trust probe

consts.go, examples/main.go, handler.go, handler_test.go, signature.go, signature_test.go
Fix signature validation errors by applying JCS before signature validation. Sometimes the request body has escape sequences (e.g. `\u0026` instead of `&`) that weren't present when Inngest Cloud created the signature
=> Apply JCS before signature validation

env.go, handler.go, handler_test.go
Add `HandlerOpts.AllowInBandSync` to control whether in-band syncs are allowed.
This is necessary because only using an env var (`INNGEST_ALLOW_IN_BAND_SYNC`) makes tests really hard to write, since env vars aren't scoped to individual tests.
=> Add AllowInBandSync handler option

handler.go, signature.go, signature_test.go
Add response signature validation functions. They're exactly the same as the request signature validation functions except they don't canonicalize the body.
This change was straightforward except for one curveball: we need to handle the JSON encoder adding a trailing newline.
=> Add response signature validation functions

funcs.go, handler.go, handler_test.go, signature.go, signature_test.go, tests/probe_test.go
- Fix trust probe not setting a response status code in certain failure scenarios.
- Add `HandlerOpts.Dev`, which controls whether the SDK is in "dev mode" (taking precedence over `INNGEST_DEV`). This is necessary for testing, since env vars bleed between tests.
- Fix introspection not responding with the correct data when in "dev mode" and an invalid signature is sent.
=> Fix trust probe status code

funcs.go, handler.go, vendor/github.com/inngest/inngest/pkg/inngest/function.go
Upstream vendor changes from: https://github.com/inngest/inngest/pull/1968
INN-4047
https://github.com/inngest/inngest/issues/1967
=> INN-4047: Convert timeout duration types to strings for

connect/connection.go
#79 changed how we subscribe to connection updates. We now store channels in struct fields instead of function arguments. This affected connection draining on the client, as we should wait for the new connection to be established before closing the original connection.
With this PR, we allow passing in an additional connection ready notification channel, which is used by draining logic to subscribe to connection status updates.
=> Fix notification to parent connection on draining reconnect

connect.go, connect/handler.go, funcs.go, handler.go, handler_test.go
Previously, we did not include the app name (app slug) in the step runtime URL, as we do in the JS and Python SDK.
This changed to always use the _full_ function ID.
This also adds graceful handling for executor requests using the old function config (i.e. requests with `fnId` query parameter that is _only_ the function ID without the app name prefix), so that requests continue to work during a deployment (before the new config is synced).
=> Generate consistent function slug

handler.go, handler_test.go
This change is necessary for testing sync failures in Cloud
=> Use error codes for signature issues

client.go, client_test.go, handler_test.go
Before these changes, events would fail to send when `INNGEST_DEV=1` because the event key wasn't set. This shouldn't be the behavior since the Dev Server doesn't require event keys
=> Make event key optional in dev

connect/handler.go, connect/handshake.go, connect/workerapi.go
- `conn.Close()` now only runs once and waits for the connection shutdown to complete before returning
-  `Connect()` will return an error if the connection limit is exceeded during the first connection
=> Wait for shutdown, expose too many connections error

client.go
Add `Client.SetOptions` and `Client.SetURL` methods. This is necessary when users don't know the `URL` option until after the client is created (we do this a lot during testing since we use a random port)
=> Add Client.SetOptions and Client.SetURL

handler.go, tests/request_context_test.go, tests/utils.go
Request context is passed to Inngest functions.
Users may have HTTP middleware that adds values to the request context, expecting those values to be accessible within Inngest functions.
=> Request context used in Inngest functions

client.go, connect.go, connect/handler.go, connect/workerapi.go, handler.go, handler_test.go, tests/invoke_test.go, tests/main_test.go, tests/parallel_test.go, tests/probe_test.go, tests/request_context_test.go, tests/send_test.go
- Fix Connect requiring signing key in dev mode.
- Fix Connect panicking when no logger passed to client.
- Fix `APIBaseURL` not used when in dev mode.
- Fix env var bleeding during tests.
=> Fix Connect requiring signing key in dev mode

.github/workflows/go.yml, event.go, go.mod, internal/event.go, step/send.go, tests/client_send_test.go, tests/step_send_test.go
- Fix `step.Send` and `step.SendMany` not accepting `GenericEvent`.
- Make `Event` derived from `GenericEvent`.
=> Fix step.Send not accepting GenericEvent

consts.go, group/group.go, headers.go, step/run.go, step/run_test.go, tests/parallel_test.go, tests/step_run_test.go, tests/step_wait_for_event_test.go, tests/utils.go, vendor/github.com/inngest/inngest/pkg/enums/opcode.go
- Move `group.Parallel` out of the `experimental` package.
- Change execution version to v2.
=> Make group.Parallel public

client.go, tests/client_send_test.go
Fix a bug where the client didn't think it was in "dev mode" when its `Dev` option was set (as opposed to the `INNGEST_DEV` env var).
=> Fix client Dev option not always considered

connect/handler.go, connect/invoke.go
I believe we are hitting two separate issues when the SDK is trying to reconnect after rotating gateways:
- SDK is not able to reconnect.
- Flushing API call is failing with a 400.
The bubbled errors are context cancelled and I believe that I've identified when it actually gets cancelled. cancelStart is called as soon as the handler.Connect call finishes. Which makes the connection fine until it needs to connect again using that same context. That startCtx is only expected to be cancelled/timed out on the first connect call.
https://github.com/inngest/inngestgo/blob/f122af6b1d151757d75365b7ac6b110d992b1ae6/connect/handler.go#L49-L50
The bad request 400 clause we are hitting is the following and it's likely because [we are not carrying the](https://github.com/inngest/inngestgo/pull/101) …
=> Fix SDK failing to reconnect when gateways are rotated

handler_test.go, internal/fn/fn.go
Add `if` support in the batch config. This conditional boolean expression, when provided, would determine which events get batched together for execution.
If the expression fails to evaluate or if it evaluates to false, the event will be treated ineligible for batching and will be scheduled for execution immediately.
=> SYS-285: Add support for conditional batching

handler.go
When using  behind a load balancer which terminates SSL, r.TLS will be nil. This results in the app being added to Inngest using HTTP.
=> Check X-Forwarded-Proto for URL building
